# Generated by Django 5.1 on 2024-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rid',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
