# Generated by Django 5.1 on 2024-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userquizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='qoute_id',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
