# Generated by Django 5.1 on 2024-08-30 13:37

import quiz.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_quiz_id_quotes_qoute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(default=quiz.utility.generate_random_id, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='qoute_id',
            field=models.CharField(default=quiz.utility.generate_random_id, max_length=5, unique=True),
        ),
    ]
