# Generated by Django 5.1 on 2024-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_quiz_id_alter_quotes_qoute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
